name: mayday
description: "Offline Disaster Response System"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.26.2
  mobile_scanner: ^7.4.0
  path_provider: ^2.1.6
  sqlite3: ^2.4.1
  sqlite3_flutter_libs: ^0.5.24
  sqflite: ^2.4.1
  cbor: ^6.5.1
  crypto: ^3.0.7
  dart_geohash: ^2.1.0
  shared_preferences: ^2.5.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/placeholder.mbtiles
    - assets/map_style.json
